network:
    logging:
        enabled: true
        level: BODY # HttpLoggingInterceptor.Level{NONE, BASIC, HEADERS, BODY}
logging:
    enabled: true
    show_hashs: false
performance:
    show_memory_leaks: true
    chuck: true
crashes:
    enabled: false
    additional_data: false
    trace_size: 10
    app_id: "00000000000000000000000000000000" # HockeyApp prod debug AppID
