network:
    logging:
        enabled: false
        level: BODY # HttpLoggingInterceptor.Level{NONE, BASIC, HEADERS, BODY}
logging:
    enabled: false
    show_hashs: false
performance:
    show_memory_leaks: false
    chuck: false
crashes:
    enabled: true
    additional_data: true
    app_id: "00000000000000000000000000000000" # HockeyApp prod distrib AppID
    max_trace: 3000
